apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pouleijn-deployment
  name: pouleijn-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pouleijn-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pouleijn-deployment
    spec:
      containers:
      - image: docker.pkg.github.com/mpouleijn/pouleijn.nl/app:0.1.0
        name: app
        resources: {}
status: {}
